server:
  port: 8082
  servlet:
    context-path: /wechat
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: com.yh.domain